// W708-6 — high-risk vertical disclaimer injection.
//
// When `spec.vertical` is one of {medical, legal, financial}, compileSpec
// stamps `manifest.disclaimer_injection` with the canonical runtime text.
// When the vertical is unset OR not in the allowlist, the field MUST NOT
// appear on the manifest. The runtime relies on the field's presence as a
// signal to wrap output; a spurious entry would mis-trigger downstream.
//
// Behavior-only: pure rule_class spec (no teacher, no GPU, no network).
// Per-test isolated $HOME so the per-user receipt secret does not collide
// across the suite (matches the W409b serial-run isolation pattern).
import { test } from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SPEC_COMPILE_URL = pathToFileURL(path.join(ROOT, 'src', 'spec-compile.js')).href;

function freshHome(label) {
  const home = path.join(os.tmpdir(), `kolm-w708-${label}-${crypto.randomBytes(4).toString('hex')}`);
  fs.mkdirSync(home, { recursive: true });
  process.env.HOME = home;
  process.env.USERPROFILE = home;
  delete process.env.RECIPE_RECEIPT_SECRET;
  delete process.env.KOLM_ARTIFACT_SECRET;
  return home;
}

function baseSpec(extra = {}) {
  return {
    job_id: 'job_w708_disclaimer_probe',
    task: 'Trivially-correct rule_class artifact for disclaimer injection probe.',
    base_model: 'none',
    recipes: [{
      id: 'rcp_probe',
      name: 'always-true probe',
      tags: ['probe'],
      source: 'function generate(input, lib) { return { ok: true }; }',
    }],
    evals: {
      spec: 'rs-1-evals',
      n: 2,
      coverage: 1.0,
      cases: [
        { id: 'ev_1', input: { x: 1 }, expected: { ok: true } },
        { id: 'ev_2', input: { x: 2 }, expected: { ok: true } },
      ],
    },
    training_stats: { approach: 'rule', verifier_accepted: true, latency_p50_us: 30 },
    ...extra,
  };
}

test('W708-6 #1 - vertical=medical injects the medical disclaimer text', async () => {
  const home = freshHome('medical');
  const outDir = path.join(home, 'artifacts');
  fs.mkdirSync(outDir, { recursive: true });
  const { compileSpec } = await import(`${SPEC_COMPILE_URL}?cache=${Date.now()}`);
  const res = await compileSpec(baseSpec({ vertical: 'medical' }), { outDir });
  assert.strictEqual(res.manifest.vertical, 'medical');
  assert.strictEqual(
    res.manifest.disclaimer_injection,
    'This output was generated by a distilled AI model. It is not a substitute for professional medical advice. Verify with a qualified professional before acting.'
  );
});

test('W708-6 #2 - vertical=legal injects the legal disclaimer text', async () => {
  const home = freshHome('legal');
  const outDir = path.join(home, 'artifacts');
  fs.mkdirSync(outDir, { recursive: true });
  const { compileSpec } = await import(`${SPEC_COMPILE_URL}?cache=${Date.now()}`);
  const res = await compileSpec(baseSpec({ vertical: 'legal' }), { outDir });
  assert.strictEqual(res.manifest.vertical, 'legal');
  assert.match(res.manifest.disclaimer_injection, /professional legal advice/);
});

test('W708-6 #3 - vertical=financial injects the financial disclaimer text', async () => {
  const home = freshHome('financial');
  const outDir = path.join(home, 'artifacts');
  fs.mkdirSync(outDir, { recursive: true });
  const { compileSpec } = await import(`${SPEC_COMPILE_URL}?cache=${Date.now()}`);
  const res = await compileSpec(baseSpec({ vertical: 'financial' }), { outDir });
  assert.strictEqual(res.manifest.vertical, 'financial');
  assert.match(res.manifest.disclaimer_injection, /professional financial advice/);
});

test('W708-6 #4 - vertical=other (not in allowlist) does NOT inject any disclaimer', async () => {
  const home = freshHome('other');
  const outDir = path.join(home, 'artifacts');
  fs.mkdirSync(outDir, { recursive: true });
  const { compileSpec } = await import(`${SPEC_COMPILE_URL}?cache=${Date.now()}`);
  const res = await compileSpec(baseSpec({ vertical: 'cooking' }), { outDir });
  assert.strictEqual(
    res.manifest.disclaimer_injection,
    undefined,
    'non-allowlisted vertical must not produce a disclaimer field'
  );
});

test('W708-6 #5 - vertical undefined does NOT inject any disclaimer', async () => {
  const home = freshHome('undef');
  const outDir = path.join(home, 'artifacts');
  fs.mkdirSync(outDir, { recursive: true });
  const { compileSpec } = await import(`${SPEC_COMPILE_URL}?cache=${Date.now()}`);
  const res = await compileSpec(baseSpec(), { outDir });
  assert.strictEqual(
    res.manifest.disclaimer_injection,
    undefined,
    'absent vertical must not produce a disclaimer field'
  );
});
