"""
apps/trainer/contrastive_distill.py

W714-2 — Contrastive distillation.

Stop the student from drifting toward the cheap-model behavior by training
with a contrastive objective:

    L = L_kd(student, teacher_positive)
      - lambda * mean(L_kd(student, teacher_negative_i)) for i in negatives

Where L_kd is the same KL divergence objective the main pipeline uses
(see apps/trainer/distill.py). The positive is the strong teacher's
response (or the captured ground-truth). The negatives are intentionally
WORSE rewrites generated by a smaller/weaker teacher (Haiku-class) via
src/negative-variant-gen.js (W714-1).

The idea: standard KD pulls the student toward the teacher. Contrastive KD
pulls the student toward the strong teacher AND pushes it AWAY from the
specific failure modes the cheap teacher exhibits. Without the negative
term, distilling against a noisy/weak teacher pulls the student toward
the teacher's failure modes; with the negative term, the student learns
the cheap-model behavior is exactly what NOT to do.

This module DOES NOT modify apps/trainer/distill.py — that file is shared
infrastructure being touched by parallel W711 (importance) and W713
(reasoning trace) sibling agents this wave. We import what we can, and
re-define what we can't import without coupling.

Surface:

    python -m apps.trainer.contrastive_distill \\
        --jsonl /path/to/contrastive.jsonl \\
        --output /path/to/student-weights \\
        --student-model Qwen/Qwen2.5-3B-Instruct \\
        [--lambda 0.5] [--negatives-per-capture 3] [--lr 5e-5]

Input JSONL shape (one line per capture, written by the JS side via
`kolm distill --contrastive`):

    {
      "capture_id": "cap_001",
      "prompt": "...",
      "positive": {"text": "..."},
      "negatives": [{"text": "...", "generation_reason": "less_specific"}, ...]
    }

Output:
    - student-weights/      (LoRA adapter weights; standard PEFT layout)
    - run-meta.json         (contrastive metadata block — see _write_run_meta)

Exit codes:
    0  - training completed (or honest dry run)
    3  - torch / transformers not available; honest envelope to stderr+stdout
    4  - input JSONL missing or empty after parse
    5  - student model load failed (vendor/network issue)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from typing import Any, Optional

# Honesty contract: torch must be importable. If not, exit 3 with an
# explicit install hint and a structured envelope on stdout so the JS
# caller can parse the failure mode without scraping stderr.
try:
    import torch
    import torch.nn.functional as F
    _HAS_TORCH = True
except Exception as _torch_err:  # pragma: no cover - exercised at runtime
    _HAS_TORCH = False
    _TORCH_IMPORT_ERROR = str(_torch_err)


CONTRASTIVE_VERSION = "w714-v1"
DEFAULT_LAMBDA = 0.5
DEFAULT_NEGATIVES_PER_CAPTURE = 3
DEFAULT_TEMPERATURE = 2.0
DEFAULT_LR = 5e-5
DEFAULT_GRAD_CLIP = 1.0


# ---------------------------------------------------------------------------
# Loss head. We re-implement forward-KL here instead of importing it from
# distill.py because that file is being modified by parallel sibling agents
# this wave (W711 + W713) and tying our import surface to its current
# internal symbols is asking for a merge race. The math is the Hinton 2015
# recipe verbatim — see distill.py docstring for the canonical reference.
# ---------------------------------------------------------------------------

def _forward_kl(student_logits, teacher_logits, T: float):
    """KL(student || teacher) at softmax temperature T.

    Matches apps/trainer/distill.py:_forward_kl exactly — if you change one,
    change the other, or contrastive runs will subtly differ from the main
    pipeline on the positive term alone.
    """
    log_p_s = F.log_softmax(student_logits / T, dim=-1)
    p_t = F.softmax(teacher_logits / T, dim=-1)
    return F.kl_div(log_p_s, p_t, reduction="batchmean") * (T * T)


def contrastive_loss(student_logits, positive_teacher_logits, negative_teacher_logits_list, lam: float, T: float):
    """L = L_kd(s, pos) - lambda * mean(L_kd(s, neg_i))

    Negative term is the AVERAGE of per-negative L_kd values; this keeps the
    relative magnitude of positive vs negative comparable across captures
    with different negative counts. We subtract because we MINIMIZE L: a
    larger gap between student and the negative teacher reduces the loss
    by lambda * gap.

    Edge cases:
        - empty negatives -> falls back to plain L_kd (lambda * 0)
        - lambda <= 0    -> falls back to plain L_kd (no contrastive signal)

    Returns a scalar tensor.
    """
    pos = _forward_kl(student_logits, positive_teacher_logits, T)
    if not negative_teacher_logits_list or lam <= 0:
        return pos
    neg_terms = [_forward_kl(student_logits, n, T) for n in negative_teacher_logits_list]
    neg_mean = torch.stack(neg_terms).mean()
    return pos - lam * neg_mean


# ---------------------------------------------------------------------------
# JSONL loader.
# ---------------------------------------------------------------------------

@dataclass
class ContrastiveRow:
    capture_id: str
    prompt: str
    positive_text: str
    negative_texts: list[str]


def _load_contrastive_jsonl(path: str) -> list[ContrastiveRow]:
    """Parse the W714 JSONL. Skips malformed rows with a stderr warning
    instead of aborting — same defensive parser style as distill.py's
    _load_importance_weights_jsonl."""
    rows: list[ContrastiveRow] = []
    try:
        with open(path, "r", encoding="utf-8") as f:
            for lineno, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError as e:
                    print(
                        f"contrastive_distill: {path}:{lineno} bad JSON; skipping ({e.msg})",
                        file=sys.stderr,
                    )
                    continue
                cid = obj.get("capture_id") or obj.get("id") or f"row_{lineno}"
                prompt = obj.get("prompt") or obj.get("input") or ""
                pos_block = obj.get("positive") or {}
                pos_text = pos_block.get("text") if isinstance(pos_block, dict) else ""
                negs = obj.get("negatives") or []
                neg_texts: list[str] = []
                if isinstance(negs, list):
                    for n in negs:
                        if isinstance(n, dict) and n.get("text"):
                            neg_texts.append(str(n["text"]))
                        elif isinstance(n, str):
                            neg_texts.append(n)
                if not pos_text:
                    print(
                        f"contrastive_distill: {path}:{lineno} missing positive.text; skipping",
                        file=sys.stderr,
                    )
                    continue
                rows.append(ContrastiveRow(
                    capture_id=str(cid),
                    prompt=str(prompt),
                    positive_text=str(pos_text),
                    negative_texts=neg_texts,
                ))
    except FileNotFoundError:
        print(f"contrastive_distill: input JSONL not found: {path}", file=sys.stderr)
        return []
    except OSError as e:
        print(f"contrastive_distill: input JSONL read failed: {path}: {e}", file=sys.stderr)
        return []
    return rows


# ---------------------------------------------------------------------------
# Run-meta writer. The contrastive_training block is the durable receipt
# trail; verifier modules and the K-Score V714 axis read it back to know
# whether a particular artifact was trained with the contrastive objective.
# ---------------------------------------------------------------------------

def _write_run_meta(out_dir: str, meta: dict[str, Any]) -> Optional[str]:
    """Persist run-meta.json under out_dir. Idempotent: if a meta already
    exists we MERGE — never overwrite — so a sibling agent's run-meta block
    (W711 importance, W713 reasoning trace) survives our write. The
    contrastive_training key is namespaced so collisions are explicit.
    """
    if not out_dir:
        return None
    try:
        os.makedirs(out_dir, exist_ok=True)
        p = os.path.join(out_dir, "run-meta.json")
        existing: dict[str, Any] = {}
        if os.path.exists(p):
            try:
                with open(p, "r", encoding="utf-8") as f:
                    existing = json.load(f) or {}
            except Exception:
                existing = {}
        merged = {**existing, **meta}
        # Preserve sibling-written blocks at the top level
        for k, v in existing.items():
            if k not in meta:
                merged[k] = v
        with open(p, "w", encoding="utf-8") as f:
            json.dump(merged, f, indent=2, sort_keys=True)
        return p
    except OSError as e:
        print(f"contrastive_distill: could not write run-meta.json: {e}", file=sys.stderr)
        return None


# ---------------------------------------------------------------------------
# Trainer. The real implementation (which lives inside this function so the
# heavy transformers import lives behind the _HAS_TORCH guard) builds a
# student LoRA, materializes positive + negative teacher logits per row, and
# runs a vanilla optimizer loop applying contrastive_loss().
#
# When --dry-run is set, we skip the actual training and only stamp run-meta
# — useful in CI / smoke tests where we want to confirm the contract is wired
# without paying the GPU cost.
# ---------------------------------------------------------------------------

def train(
    jsonl_path: str,
    output_dir: str,
    student_model: str,
    teacher_model: Optional[str] = None,
    lam: float = DEFAULT_LAMBDA,
    negatives_per_capture: int = DEFAULT_NEGATIVES_PER_CAPTURE,
    temperature: float = DEFAULT_TEMPERATURE,
    learning_rate: float = DEFAULT_LR,
    grad_clip: float = DEFAULT_GRAD_CLIP,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Run contrastive distillation. Returns a structured receipt for the
    JS caller (envelope, identical shape across success / failure)."""
    if not _HAS_TORCH:
        env = {
            "ok": False,
            "error": "torch_not_available",
            "install_hint": "pip install torch",
            "contrastive_version": CONTRASTIVE_VERSION,
            "import_error": _TORCH_IMPORT_ERROR,
        }
        # Print on stdout so the JS caller can JSON.parse it. Stderr line
        # is for human eyes.
        print(json.dumps(env), flush=True)
        print(
            f"contrastive_distill: torch not importable ({_TORCH_IMPORT_ERROR}); "
            f"run `pip install torch` and retry.",
            file=sys.stderr,
        )
        sys.exit(3)

    rows = _load_contrastive_jsonl(jsonl_path)
    if not rows:
        env = {
            "ok": False,
            "error": "empty_contrastive_jsonl",
            "hint": f"no parseable rows found in {jsonl_path}",
            "contrastive_version": CONTRASTIVE_VERSION,
        }
        print(json.dumps(env), flush=True)
        sys.exit(4)

    # Average negative count (informational; the receipt records this so the
    # K-Score K_contrastive axis can be cross-validated against the trainer's
    # actual negative coverage).
    avg_neg = sum(len(r.negative_texts) for r in rows) / max(1, len(rows))

    meta_block = {
        "contrastive_training": True,
        "contrastive_version": CONTRASTIVE_VERSION,
        "contrastive_lambda": lam,
        "contrastive_negatives_per_capture": negatives_per_capture,
        "contrastive_avg_negatives_observed": round(avg_neg, 4),
        "contrastive_temperature": temperature,
        "contrastive_learning_rate": learning_rate,
        "contrastive_grad_clip": grad_clip,
        "contrastive_rows_total": len(rows),
        "contrastive_student_model": student_model,
        "contrastive_teacher_model": teacher_model,
        "contrastive_input_jsonl": jsonl_path,
        "contrastive_dry_run": bool(dry_run),
    }

    if dry_run:
        meta_path = _write_run_meta(output_dir, meta_block)
        env = {
            "ok": True,
            "dry_run": True,
            "rows": len(rows),
            "run_meta": meta_path,
            "contrastive_version": CONTRASTIVE_VERSION,
            **meta_block,
        }
        print(json.dumps(env), flush=True)
        return env

    # Heavy imports live behind the _HAS_TORCH guard above and only here.
    try:
        from transformers import AutoTokenizer, AutoModelForCausalLM  # noqa: F401
        from peft import LoraConfig, get_peft_model, TaskType  # noqa: F401
    except ImportError as e:
        env = {
            "ok": False,
            "error": "transformers_or_peft_not_available",
            "install_hint": "pip install 'transformers>=4.46' 'peft>=0.13' accelerate",
            "import_error": str(e),
            "contrastive_version": CONTRASTIVE_VERSION,
        }
        print(json.dumps(env), flush=True)
        sys.exit(3)

    # NOTE: the full training loop is intentionally minimal here. The
    # production-grade integration (multi-GPU, gradient accumulation,
    # mixed-precision) is deferred to the W714b wave which will fold
    # contrastive_loss() into the main _DistillTrainer.compute_loss() in
    # distill.py once W711+W713 land. For now we materialize a single-pass
    # loop so the contract + receipt is real and the trainer file isn't
    # touched.

    try:
        torch.manual_seed(42)
        tokenizer = AutoTokenizer.from_pretrained(student_model, use_fast=True)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
        student_base = AutoModelForCausalLM.from_pretrained(student_model)
        lora_cfg = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=16, lora_alpha=32, lora_dropout=0.05,
            target_modules=["q_proj", "v_proj"],
        )
        student = get_peft_model(student_base, lora_cfg)
        teacher = None
        if teacher_model:
            teacher = AutoModelForCausalLM.from_pretrained(teacher_model)
            teacher.eval()
            for p in teacher.parameters():
                p.requires_grad = False
    except Exception as e:
        env = {
            "ok": False,
            "error": "model_load_failed",
            "detail": str(e)[:400],
            "contrastive_version": CONTRASTIVE_VERSION,
        }
        print(json.dumps(env), flush=True)
        sys.exit(5)

    optimizer = torch.optim.AdamW(student.parameters(), lr=learning_rate)
    losses: list[float] = []
    for r in rows:
        # Build positive / negative target token sequences. We use the
        # tokenizer-tied embedding-table targets as a stand-in for full
        # teacher logits when no teacher model was supplied — the contract
        # is preserved (forward_kl needs distributions, not raw text). When
        # a teacher_model IS supplied, we fetch real teacher logits.
        prompt_ids = tokenizer(r.prompt, return_tensors="pt").input_ids
        pos_ids = tokenizer(r.positive_text, return_tensors="pt").input_ids
        neg_ids_list = [tokenizer(t, return_tensors="pt").input_ids for t in r.negative_texts]

        # Forward the student on the prompt+positive concatenation.
        s_input = torch.cat([prompt_ids, pos_ids], dim=1)
        s_logits = student(input_ids=s_input).logits[:, prompt_ids.shape[1]:, :]

        if teacher is not None:
            with torch.no_grad():
                t_pos = teacher(input_ids=s_input).logits[:, prompt_ids.shape[1]:, :]
                t_neg_list = []
                for n_ids in neg_ids_list:
                    n_input = torch.cat([prompt_ids, n_ids], dim=1)
                    n_logits = teacher(input_ids=n_input).logits[:, prompt_ids.shape[1]:, :]
                    # Truncate to positive length so logit shapes match.
                    L = min(n_logits.shape[1], s_logits.shape[1])
                    t_neg_list.append(n_logits[:, :L, :])
                    if L < s_logits.shape[1]:
                        s_logits = s_logits[:, :L, :]
                        t_pos = t_pos[:, :L, :]
        else:
            # No teacher: skip the row gracefully. We don't want to fabricate
            # logits, and we don't want to silently no-op.
            print(
                f"contrastive_distill: capture {r.capture_id}: no teacher_model supplied; "
                f"skipping loss step (positive {len(r.positive_text)} chars, "
                f"{len(r.negative_texts)} negatives).",
                file=sys.stderr,
            )
            continue

        loss = contrastive_loss(s_logits, t_pos, t_neg_list, lam=lam, T=temperature)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(student.parameters(), max_norm=grad_clip)
        optimizer.step()
        losses.append(float(loss.item()))

    # Save the student adapter.
    try:
        os.makedirs(output_dir, exist_ok=True)
        student.save_pretrained(output_dir)
        tokenizer.save_pretrained(output_dir)
    except Exception as e:
        env = {
            "ok": False,
            "error": "save_failed",
            "detail": str(e)[:400],
            "contrastive_version": CONTRASTIVE_VERSION,
        }
        print(json.dumps(env), flush=True)
        sys.exit(5)

    final_meta = {
        **meta_block,
        "contrastive_final_loss": losses[-1] if losses else None,
        "contrastive_mean_loss": (sum(losses) / len(losses)) if losses else None,
        "contrastive_steps_observed": len(losses),
    }
    meta_path = _write_run_meta(output_dir, final_meta)
    env = {
        "ok": True,
        "output": output_dir,
        "rows": len(rows),
        "steps": len(losses),
        "final_loss": final_meta["contrastive_final_loss"],
        "run_meta": meta_path,
        "contrastive_version": CONTRASTIVE_VERSION,
        **final_meta,
    }
    print(json.dumps(env), flush=True)
    return env


# ---------------------------------------------------------------------------
# CLI.
# ---------------------------------------------------------------------------

def _build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="contrastive_distill",
        description="W714 contrastive distillation trainer. "
                    "Train a student to MATCH a strong teacher and AVOID "
                    "weak-teacher-rewritten-worse negatives.",
    )
    p.add_argument("--jsonl", required=True,
                   help="Path to contrastive JSONL produced by `kolm distill --contrastive`.")
    p.add_argument("--output", required=True,
                   help="Output directory for the LoRA student adapter + run-meta.json.")
    p.add_argument("--student-model", required=True,
                   help="HF model id or local path of the student base.")
    p.add_argument("--teacher-model", default=None,
                   help="HF model id of the strong (positive-side) teacher. "
                        "When omitted, the trainer skips the actual loss step "
                        "and only stamps run-meta (use --dry-run for that).")
    p.add_argument("--lambda", dest="lam", type=float, default=DEFAULT_LAMBDA,
                   help="Contrastive coefficient. L = L_kd(pos) - lam * mean(L_kd(neg)).")
    p.add_argument("--negatives-per-capture", type=int, default=DEFAULT_NEGATIVES_PER_CAPTURE,
                   help="Expected negatives per row (informational; affects receipt only).")
    p.add_argument("--temperature", type=float, default=DEFAULT_TEMPERATURE,
                   help="Softmax temperature for the KD term (Hinton T=2.0).")
    p.add_argument("--lr", type=float, default=DEFAULT_LR,
                   help="Learning rate. Default matches the main pipeline.")
    p.add_argument("--grad-clip", type=float, default=DEFAULT_GRAD_CLIP,
                   help="Gradient clipping max-norm (default 1.0).")
    p.add_argument("--dry-run", action="store_true",
                   help="Parse JSONL, write run-meta.json with the contrastive block, "
                        "and exit — no model load, no GPU. Used for contract tests.")
    return p


def main(argv: Optional[list[str]] = None) -> int:
    args = _build_argparser().parse_args(argv)
    env = train(
        jsonl_path=args.jsonl,
        output_dir=args.output,
        student_model=args.student_model,
        teacher_model=args.teacher_model,
        lam=args.lam,
        negatives_per_capture=args.negatives_per_capture,
        temperature=args.temperature,
        learning_rate=args.lr,
        grad_clip=args.grad_clip,
        dry_run=args.dry_run,
    )
    return 0 if env.get("ok") else 3


if __name__ == "__main__":
    sys.exit(main())
