#!/usr/bin/env python3
"""T2.5 — One-shot "trained adapter -> public model" publisher.

Takes a directory holding a trained LoRA adapter (the output of
workers/distill/scripts/train_lora.py) plus its training manifest + eval
summary and turns it into something the world can download and run:

  1. GGUF  — convert the (merged) HF weights to GGUF + quantize to one or more
             llama.cpp k-quants (Q4_K_M, Q5_K_M, ...). Opt-in via --quants; the
             tooling (llama.cpp's convert_hf_to_gguf.py + the llama-quantize
             binary) is located on PATH / $KOLM_LLAMACPP_DIR. When it is NOT
             present the run does NOT fail: the summary carries a
             "gguf_tooling_unavailable" status and we still emit the model card
             + Modelfile + (optionally) push the safetensors.
  2. README — a HuggingFace Hub model card, generated by REUSING the existing
             src/hf-modelcard.js writeModelCard() (spawned via `node`). The
             passport.json + benchmark JSON in the adapter dir drive it. We do
             NOT reinvent the card here.
  3. Modelfile — an Ollama Modelfile pointing at the primary GGUF, written
             locally so `ollama create` (or a human) can consume it.
  4. HF push — opt-in via --publish + --hf <user/repo>. Requires the HF_TOKEN
             env var (preflighted; missing -> exit 2 before any network call).
  5. Ollama — opt-in via --ollama <name>; runs `ollama create <name> -f
             <Modelfile>` only when the ollama binary is on PATH.

SAFETY (opt-in by design):
  - Default behaviour (no --publish, no --ollama) is a DRY RUN: produce the
    README.md + Modelfile (+ GGUF if tooling present) locally, touch no
    network and no ollama daemon.
  - HF/Ollama side effects fire ONLY behind their explicit flags.

Output: a machine-readable JSON summary is printed as the LAST stdout line.
Human-facing progress goes to stderr.

Exit codes:
  0  ok (dry-run or a real publish that completed)
  2  bad args OR a required dependency / preflight is missing
     (e.g. --publish without HF_TOKEN, or --quants without a model dir)
  3  a required input path is missing (the adapter dir / its contents)
  4  a runtime / network step raised

Heavy + optional deps (huggingface_hub, the gguf tooling, the ollama binary)
are imported / resolved lazily INSIDE functions, so `--help` and `--dry-run`
work on a box with none of them installed.
"""

# T1.7 — Windows cp950/cp1252 emoji crash guard. Importing _console runs the
# UTF-8 shim at module load; teacher-sourced strings in manifests can carry
# emoji + CJK.
from _console import setup_utf8 as _setup_utf8  # noqa: F401 — import side-effect

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
import traceback
from pathlib import Path

VERSION = "t2.5-v1"

# llama.cpp k-quant types we know how to ask llama-quantize for. This is an
# allow-list used to validate --quants and to map a quant -> output filename.
# It is intentionally a superset of the default so power users can request more.
KNOWN_QUANTS = (
    "Q2_K", "Q3_K_S", "Q3_K_M", "Q3_K_L",
    "Q4_K_S", "Q4_K_M", "Q5_K_S", "Q5_K_M",
    "Q6_K", "Q8_0", "IQ4_XS", "F16", "BF16",
)
DEFAULT_QUANTS = ("Q4_K_M", "Q5_K_M")


# ---------------------------------------------------------------------------
# Tiny logging + exit helpers. All human output -> stderr so the LAST stdout
# line is always the machine-readable summary.
# ---------------------------------------------------------------------------
def _log(msg):
    sys.stderr.write(f"[publish] {msg}\n")
    sys.stderr.flush()


def _emit_summary(summary):
    """Print the machine-readable JSON summary as the LAST stdout line."""
    sys.stdout.write(json.dumps(summary, ensure_ascii=False) + "\n")
    sys.stdout.flush()


def _fail(code, summary, reason):
    """Emit a failure summary (still the last stdout line) and exit `code`."""
    summary["ok"] = False
    summary["reason"] = reason
    _log(f"FAIL ({code}): {reason}")
    _emit_summary(summary)
    sys.exit(code)


def parse_args(argv=None):
    p = argparse.ArgumentParser(
        prog="kolm-publish",
        description="Trained adapter -> GGUF + HF model card + (opt-in) HF/Ollama publish.",
        add_help=True,
    )
    p.add_argument("--adapter", required=True,
                   help="Trained adapter directory (holds training-summary.json, "
                        "eval-mixeval-hard.json, passport.json, and the merged HF "
                        "weights / adapter).")
    p.add_argument("--quants", default=",".join(DEFAULT_QUANTS),
                   help="Comma list of llama.cpp k-quant types to produce, e.g. "
                        "'Q4_K_M,Q5_K_M'. Pass an empty string to skip GGUF "
                        f"entirely. Known: {', '.join(KNOWN_QUANTS)}.")
    p.add_argument("--hf", dest="hf_repo", default=None,
                   help="HuggingFace repo id (user/repo). With --publish this is "
                        "the push target; without --publish it only annotates the "
                        "model card.")
    p.add_argument("--ollama", dest="ollama_name", default=None,
                   help="Ollama model name. When set AND the ollama binary is on "
                        "PATH, runs `ollama create <name> -f <Modelfile>`.")
    p.add_argument("--publish", action="store_true",
                   help="Actually PUSH to HuggingFace Hub (requires --hf + HF_TOKEN). "
                        "Without this flag the run is a dry run for the HF step.")
    p.add_argument("--dry-run", dest="dry_run", action="store_true", default=None,
                   help="Force dry run (default unless --publish/--ollama is set). "
                        "Produces README.md + Modelfile (+ GGUF if tooling present) "
                        "locally and touches no network / ollama daemon.")
    p.add_argument("--out", dest="out_dir", default=None,
                   help="Where README/Modelfile/gguf land. Default: <adapter>/publish/.")
    p.add_argument("--license", default=None,
                   help="License id for the model card (default: passport.json or apache-2.0).")
    p.add_argument("--base-model", dest="base_model", default=None,
                   help="Override base_model on the card (default: from passport/manifest).")
    p.add_argument("--weights-dir", dest="weights_dir", default=None,
                   help="Explicit HF-format weights dir to convert to GGUF "
                        "(default: auto-detected merged dir under --adapter).")
    return p.parse_args(argv)


# ---------------------------------------------------------------------------
# Input discovery. The adapter dir is the contract surface; we read the
# training manifest + eval summary from it and locate a passport + the HF
# weights to convert.
# ---------------------------------------------------------------------------
def _read_json(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def _find_first(adapter, names):
    """Return the first existing path among <adapter>/<name> and one level of
    common subdirs (merged/, merged/qwen-merged/, student/)."""
    subdirs = ["", "merged", os.path.join("merged", "qwen-merged"), "student"]
    for sub in subdirs:
        for name in names:
            cand = adapter / sub / name if sub else adapter / name
            if cand.exists():
                return cand
    return None


def _detect_weights_dir(adapter):
    """Find a HF-format weights dir (has config.json + a safetensors/bin shard)
    to feed convert_hf_to_gguf.py. Prefers a merged full-weights dir over the
    raw LoRA adapter (LoRA adapters alone are not directly GGUF-convertible)."""
    candidates = [
        adapter / "merged" / "qwen-merged",
        adapter / "merged",
        adapter / "merged-fp16",
        adapter / "student-merged",
        adapter,
    ]
    for c in candidates:
        try:
            if not c.is_dir():
                continue
            if not (c / "config.json").exists():
                continue
            has_weights = any(
                p.suffix in (".safetensors", ".bin") or p.name.endswith(".gguf")
                for p in c.iterdir() if p.is_file()
            )
            if has_weights:
                return c
        except OSError:
            continue
    return None


# ---------------------------------------------------------------------------
# GGUF — locate llama.cpp tooling, convert, quantize. Never hard-fails the run.
# ---------------------------------------------------------------------------
def _locate_gguf_tooling():
    """Return (converter_py | None, quantize_bin | None, search_notes[]).

    converter_py: path to llama.cpp's convert_hf_to_gguf.py (or legacy
                  convert-hf-to-gguf.py). Resolved from $KOLM_LLAMACPP_DIR,
                  $LLAMA_CPP_DIR, then a few well-known dirs.
    quantize_bin: path/name of the llama-quantize (or legacy `quantize`)
                  binary, resolved on PATH or alongside the converter.
    """
    notes = []
    search_dirs = []
    for env in ("KOLM_LLAMACPP_DIR", "LLAMA_CPP_DIR", "LLAMACPP_DIR"):
        v = os.environ.get(env)
        if v:
            search_dirs.append(v)
    # Common checkout locations relative to the repo + home.
    home = os.path.expanduser("~")
    search_dirs += [
        os.path.join(home, "llama.cpp"),
        os.path.join(home, ".kolm", "llama.cpp"),
        "/opt/llama.cpp",
        os.path.join(os.getcwd(), "llama.cpp"),
    ]

    converter = None
    converter_names = ("convert_hf_to_gguf.py", "convert-hf-to-gguf.py")
    for d in search_dirs:
        if not d or not os.path.isdir(d):
            continue
        for name in converter_names:
            cand = os.path.join(d, name)
            if os.path.exists(cand):
                converter = cand
                break
        if converter:
            break
    if not converter:
        # Maybe it is on PATH as a console script.
        for name in converter_names:
            found = shutil.which(name)
            if found:
                converter = found
                break
    if not converter:
        notes.append(
            "convert_hf_to_gguf.py not found (looked in $KOLM_LLAMACPP_DIR / "
            "$LLAMA_CPP_DIR / ~/llama.cpp / /opt/llama.cpp / ./llama.cpp / PATH)"
        )

    # llama-quantize binary (renamed from `quantize` upstream).
    quantize_bin = None
    for binname in ("llama-quantize", "quantize"):
        found = shutil.which(binname)
        if found:
            quantize_bin = found
            break
    if not quantize_bin and converter:
        conv_dir = os.path.dirname(converter)
        for binname in ("llama-quantize", "quantize",
                        "llama-quantize.exe", "quantize.exe"):
            for sub in ("", "build", os.path.join("build", "bin")):
                cand = os.path.join(conv_dir, sub, binname) if sub else os.path.join(conv_dir, binname)
                if os.path.exists(cand):
                    quantize_bin = cand
                    break
            if quantize_bin:
                break
    if not quantize_bin:
        notes.append(
            "llama-quantize binary not found on PATH or alongside the converter "
            "(build llama.cpp, or set $KOLM_LLAMACPP_DIR to a built checkout)"
        )
    return converter, quantize_bin, notes


def _gguf_filename(model_stem, quant):
    return f"{model_stem}.{quant}.gguf"


def build_gguf(weights_dir, out_dir, quants, model_stem):
    """Convert weights_dir -> F16 GGUF, then quantize to each requested k-quant.

    Returns (gguf_list, status). status is one of:
      'produced'                 — at least one quant written
      'gguf_tooling_unavailable' — converter or quantize binary missing
      'no_quants_requested'      — caller passed an empty --quants
      'failed'                   — tooling present but a step raised
    gguf_list: [{quant, path, bytes}] for every quant successfully written.
    """
    if not quants:
        return [], "no_quants_requested"

    converter, quantize_bin, notes = _locate_gguf_tooling()
    if not converter or not quantize_bin:
        for n in notes:
            _log(f"gguf: {n}")
        return [], "gguf_tooling_unavailable"

    os.makedirs(out_dir, exist_ok=True)
    # Step 1 — convert to a full-precision F16 GGUF once; quantize from it.
    f16_path = os.path.join(out_dir, f"{model_stem}.F16.gguf")
    _log(f"gguf: converting {weights_dir} -> {f16_path} via {converter}")
    conv_cmd = [sys.executable, converter, str(weights_dir),
                "--outfile", f16_path, "--outtype", "f16"]
    res = subprocess.run(conv_cmd, check=False)
    if res.returncode != 0 or not os.path.exists(f16_path):
        _log(f"gguf: convert step exited {res.returncode}")
        return [], "failed"

    produced = []
    for quant in quants:
        if quant in ("F16", "BF16"):
            # The base conversion already is F16; just record it.
            if quant == "F16":
                produced.append({
                    "quant": "F16",
                    "path": f16_path,
                    "bytes": os.path.getsize(f16_path),
                })
            continue
        out_path = os.path.join(out_dir, _gguf_filename(model_stem, quant))
        _log(f"gguf: quantize {quant} -> {out_path}")
        q_cmd = [quantize_bin, f16_path, out_path, quant]
        res = subprocess.run(q_cmd, check=False)
        if res.returncode != 0 or not os.path.exists(out_path):
            _log(f"gguf: quantize {quant} exited {res.returncode} (skipping)")
            continue
        produced.append({
            "quant": quant,
            "path": out_path,
            "bytes": os.path.getsize(out_path),
        })
    if not produced:
        return [], "failed"
    return produced, "produced"


# ---------------------------------------------------------------------------
# Model card — REUSE src/hf-modelcard.js writeModelCard via a spawned node.
# We DO NOT reimplement the card here.
# ---------------------------------------------------------------------------
def _repo_root():
    # workers/distill/scripts/publish.py -> repo root is three parents up.
    return Path(__file__).resolve().parents[3]


def _ensure_passport(adapter, manifest, eval_summary, base_model_override, license_override):
    """writeModelCard() requires a passport.json in the artifact dir. If the
    adapter already has one we keep it. Otherwise we synthesize a minimal
    passport (kolm.passport/1 shape that hf-modelcard.js reads) from the
    training manifest + eval summary, write it next to the README, and return
    its directory so writeModelCard can find it.

    Returns (artifact_dir, passport_path, synthesized: bool).
    """
    existing = _find_first(adapter, ["passport.json"])
    if existing:
        return existing.parent, existing, False

    # Synthesize from the manifest. Map the training-summary.json shape onto the
    # passport fields hf-modelcard.js consumes (student_base/base_model, recipe,
    # dataset, council, id, license).
    m = manifest or {}
    repro = m.get("reproducibility", {}) if isinstance(m, dict) else {}
    eff = m.get("efficiency", {}) if isinstance(m, dict) else {}
    base_model = (base_model_override or m.get("student_base")
                  or m.get("base_model") or repro.get("student_base"))
    run_id = (repro.get("recipe_name") or m.get("recipe_name")
              or adapter.name or "kolm-distilled-model")
    passport = {
        "schema": "kolm.passport/1",
        "id": run_id,
        "student_base": base_model,
        "base_model": base_model,
        "license": license_override or m.get("license") or "apache-2.0",
        "language": "en",
        "tags": ["kolm", "distilled"],
        "recipe": {
            "lora_rank": m.get("lora_rank"),
            "lora_alpha": m.get("lora_alpha"),
            "epochs": m.get("epochs"),
            "batch_size": m.get("batch_size"),
            "lr": m.get("lr"),
            "precision": eff.get("precision"),
        },
        "dataset": {
            "pairs_collected": m.get("pairs"),
        },
        "reproducibility": repro,
    }
    if eval_summary and isinstance(eval_summary, dict):
        passport["holdout"] = {
            "n": eval_summary.get("questions_scored"),
            "mean_score": eval_summary.get("mean_score"),
            "arena_correlation_estimate": eval_summary.get("arena_correlation_estimate"),
            "cot_contaminated": eval_summary.get("cot_contaminated"),
        }
    # Datasets: a Hub-style slug so the card frontmatter has the required field.
    if run_id:
        passport["datasets"] = [f"kolm/{run_id}-seeds"]

    # Write into the out dir (the artifact dir writeModelCard reads from).
    return None, passport, True


def write_model_card(artifact_dir, out_dir, manifest, eval_summary,
                     hf_repo, base_model, license_id):
    """Spawn node to call writeModelCard({artifactDir, options}). The benchmark
    is the eval summary if present. Returns (readme_path | None, note).

    We stage a working artifact dir containing passport.json (+ benchmark JSON)
    so hf-modelcard.js's loader finds them, then point writeModelCard at it with
    subdir='' so the README lands in our out dir.
    """
    root = _repo_root()
    modelcard_js = root / "src" / "hf-modelcard.js"
    if not modelcard_js.exists():
        return None, f"hf-modelcard.js not found at {modelcard_js}"

    node = shutil.which("node") or shutil.which("node.exe")
    if not node:
        return None, "node not on PATH (needed to render the model card via src/hf-modelcard.js)"

    os.makedirs(out_dir, exist_ok=True)

    # Resolve / synthesize the passport into the out dir so writeModelCard can
    # read it with a stable layout.
    _adir, passport, synthesized = _ensure_passport(
        artifact_dir if artifact_dir else Path(out_dir),
        manifest, eval_summary, base_model, license_id,
    )
    staged_passport = os.path.join(out_dir, "passport.json")
    if synthesized:
        with open(staged_passport, "w", encoding="utf-8") as f:
            json.dump(passport, f, ensure_ascii=False, indent=2)
        _log(f"model-card: synthesized passport.json from training manifest -> {staged_passport}")
    else:
        # Copy the real passport into the out dir so the card + repo are colocated.
        try:
            shutil.copyfile(passport, staged_passport)
        except Exception:
            staged_passport = str(passport)  # fall back to reading in place

    # Stage the benchmark (eval summary) the card reader expects.
    benchmark_path = None
    if eval_summary and isinstance(eval_summary, dict):
        benchmark_path = os.path.join(out_dir, "benchmark-summary.json")
        # hf-modelcard.js keys the benchmark by model id; wrap the flat eval
        # summary under the run id so _benchmarkRowFor finds a row.
        run_id = (passport.get("id") if isinstance(passport, dict) else None) or "model"
        wrapped = {run_id: eval_summary}
        with open(benchmark_path, "w", encoding="utf-8") as f:
            json.dump(wrapped, f, ensure_ascii=False, indent=2)

    # Build the node one-shot. We import writeModelCard and call it with subdir=''
    # so the README lands directly in out_dir, and pass explicit passport/benchmark
    # paths so there is no ambiguity.
    options = {
        "passportPath": staged_passport,
        "subdir": "",
        "target_repo": hf_repo or None,
        "license": license_id or None,
        "base_model": base_model or None,
    }
    if benchmark_path:
        options["benchmarkPath"] = benchmark_path
    node_payload = {
        "modelcard": str(modelcard_js),
        "artifactDir": out_dir,
        "options": options,
    }
    # The node program reads its config from argv[1] (a JSON string) to avoid
    # quoting hell inside -e on Windows.
    node_prog = (
        "const cfg=JSON.parse(process.argv[1]);"
        "const url=require('url').pathToFileURL(cfg.modelcard).href;"
        "import(url).then(m=>{"
        "const r=m.writeModelCard({artifactDir:cfg.artifactDir,options:cfg.options});"
        "process.stdout.write(JSON.stringify(r));"
        "}).catch(e=>{console.error(String(e&&e.stack||e));process.exit(7);});"
    )
    res = subprocess.run(
        [node, "-e", node_prog, json.dumps(node_payload)],
        capture_output=True, text=True, check=False,
    )
    if res.returncode != 0:
        return None, f"node writeModelCard exited {res.returncode}: {(res.stderr or '').strip()[:300]}"
    try:
        out = json.loads((res.stdout or "").strip().splitlines()[-1])
    except Exception:
        return None, f"could not parse writeModelCard output: {(res.stdout or '')[:200]}"
    readme_path = out.get("path")
    if not readme_path or not os.path.exists(readme_path):
        return None, f"writeModelCard reported {readme_path} but it is not on disk"
    return readme_path, "ok"


# ---------------------------------------------------------------------------
# Modelfile — Ollama. Points at the primary GGUF (first requested quant).
# ---------------------------------------------------------------------------
def write_modelfile(out_dir, gguf_list, manifest, system_prompt=None):
    """Write an Ollama Modelfile referencing the primary GGUF. When no GGUF was
    produced we still write a Modelfile with a commented FROM line so a human
    can fill it in after building the GGUF. Returns the Modelfile path."""
    os.makedirs(out_dir, exist_ok=True)
    modelfile_path = os.path.join(out_dir, "Modelfile")
    primary = gguf_list[0] if gguf_list else None
    lines = []
    if primary:
        # Reference by basename so the Modelfile is portable next to the gguf.
        lines.append(f"FROM ./{os.path.basename(primary['path'])}")
    else:
        lines.append("# No GGUF was produced in this run (gguf tooling unavailable).")
        lines.append("# After building a GGUF, point FROM at it, e.g.:")
        lines.append("# FROM ./model.Q4_K_M.gguf")
    # A conservative default chat template + stop tokens for Qwen-family chat;
    # callers can override post-hoc.
    sys_prompt = system_prompt or "You are a helpful assistant."
    lines.append("")
    lines.append(f'SYSTEM """{sys_prompt}"""')
    lines.append("")
    lines.append('PARAMETER temperature 0.7')
    lines.append('PARAMETER stop "<|im_end|>"')
    lines.append('PARAMETER stop "<|endoftext|>"')
    with open(modelfile_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return modelfile_path


# ---------------------------------------------------------------------------
# HuggingFace push — opt-in, preflighted. Uploads the out dir (README + gguf).
# ---------------------------------------------------------------------------
def push_to_hf(out_dir, hf_repo):
    """Upload out_dir to the HF Hub repo. Caller MUST have preflighted HF_TOKEN.
    Returns {pushed, repo, url|None, reason?}. Raises nothing — any failure is
    returned in the dict (caller maps to exit 4)."""
    token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
    if not token:
        return {"pushed": False, "repo": hf_repo, "url": None,
                "reason": "HF_TOKEN not set"}
    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError as e:
        return {"pushed": False, "repo": hf_repo, "url": None,
                "reason": f"huggingface_hub not installed: {e}"}
    try:
        create_repo(hf_repo, token=token, exist_ok=True, repo_type="model")
        api = HfApi(token=token)
        api.upload_folder(
            folder_path=out_dir,
            repo_id=hf_repo,
            repo_type="model",
            commit_message=f"kolm publish {VERSION}",
        )
        return {
            "pushed": True,
            "repo": hf_repo,
            "url": f"https://huggingface.co/{hf_repo}",
        }
    except Exception as e:
        return {"pushed": False, "repo": hf_repo, "url": None,
                "reason": f"{e.__class__.__name__}: {e}"}


# ---------------------------------------------------------------------------
# Ollama create — opt-in, only when the binary is present.
# ---------------------------------------------------------------------------
def ollama_create(name, modelfile_path):
    """Run `ollama create <name> -f <Modelfile>` when ollama is on PATH.
    Returns {created, name, reason?}."""
    ollama = shutil.which("ollama") or shutil.which("ollama.exe")
    if not ollama:
        return {"created": False, "name": name, "reason": "ollama binary not on PATH"}
    try:
        res = subprocess.run(
            [ollama, "create", name, "-f", modelfile_path],
            capture_output=True, text=True, check=False,
        )
        if res.returncode != 0:
            return {"created": False, "name": name,
                    "reason": f"ollama create exited {res.returncode}: {(res.stderr or '').strip()[:200]}"}
        return {"created": True, "name": name}
    except Exception as e:
        return {"created": False, "name": name,
                "reason": f"{e.__class__.__name__}: {e}"}


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main(argv=None):
    args = parse_args(argv)

    # Effective dry-run: default true unless an explicit publish/ollama side
    # effect is requested. An explicit --dry-run always forces dry run.
    if args.dry_run is True:
        dry_run = True
    elif args.publish or args.ollama_name:
        dry_run = False
    else:
        dry_run = True

    quants = [q.strip() for q in (args.quants or "").split(",") if q.strip()]
    bad_quants = [q for q in quants if q not in KNOWN_QUANTS]

    adapter = Path(args.adapter).expanduser()
    out_dir = (Path(args.out_dir).expanduser() if args.out_dir
               else adapter / "publish")

    # Skeleton summary; mutated as we go so even early failures are well-formed.
    summary = {
        "ok": True,
        "version": VERSION,
        "dry_run": dry_run,
        "gguf": [],
        "gguf_status": "not_attempted",
        "readme_path": None,
        "modelfile_path": None,
        "hf": {"pushed": False, "repo": args.hf_repo, "url": None},
        "ollama": {"created": False, "name": args.ollama_name},
        "manifest_present": False,
        "eval_present": False,
    }

    # --- Bad args (argparse-level semantics we enforce ourselves) -> exit 2 ---
    if bad_quants:
        _fail(2, summary,
              f"unknown quant(s) {bad_quants}; known: {', '.join(KNOWN_QUANTS)}")
    if args.publish and not args.hf_repo:
        _fail(2, summary, "--publish requires --hf <user/repo>")

    # --- HF_TOKEN preflight BEFORE any work when a real push is requested. ---
    if args.publish:
        if not (os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")):
            _fail(2, summary,
                  "--publish requires the HF_TOKEN environment variable "
                  "(export HF_TOKEN=hf_...); refusing to push without it")

    # --- Required input: the adapter dir must exist -> exit 3 ---
    if not adapter.exists() or not adapter.is_dir():
        _fail(3, summary, f"--adapter path missing or not a directory: {adapter}")

    # --- Read the training manifest + eval summary from the adapter dir. ---
    manifest_path = _find_first(adapter, ["training-summary.json"])
    eval_path = _find_first(adapter, ["eval-mixeval-hard.json", "eval-mixeval.json"])
    manifest = _read_json(manifest_path) if manifest_path else None
    eval_summary = _read_json(eval_path) if eval_path else None
    summary["manifest_present"] = manifest is not None
    summary["eval_present"] = eval_summary is not None
    if manifest_path:
        _log(f"manifest: {manifest_path}")
    else:
        _log("manifest: training-summary.json not found (card will be sparse)")
    if eval_path:
        _log(f"eval: {eval_path}")
    else:
        _log("eval: eval summary not found (card will omit benchmark numbers)")

    os.makedirs(out_dir, exist_ok=True)
    try:
        # --- 1. GGUF (opt-in via --quants; never hard-fails the run) ---------
        weights_dir = (Path(args.weights_dir).expanduser() if args.weights_dir
                       else _detect_weights_dir(adapter))
        model_stem = adapter.name.replace(" ", "-") or "model"
        if quants:
            if weights_dir is None:
                _log("gguf: no HF-format weights dir found under --adapter "
                     "(need a merged dir with config.json + weights); skipping GGUF")
                summary["gguf_status"] = "no_weights_dir"
            else:
                gguf_list, gguf_status = build_gguf(
                    weights_dir, str(out_dir), quants, model_stem)
                summary["gguf"] = gguf_list
                summary["gguf_status"] = gguf_status
        else:
            summary["gguf_status"] = "no_quants_requested"

        # --- 2. Model card (REUSE src/hf-modelcard.js) -----------------------
        artifact_dir = manifest_path.parent if manifest_path else adapter
        readme_path, card_note = write_model_card(
            artifact_dir, str(out_dir), manifest, eval_summary,
            args.hf_repo, args.base_model, args.license,
        )
        summary["readme_path"] = readme_path
        if not readme_path:
            # The card is core to the publish contract; treat as runtime failure.
            _fail(4, summary, f"model card generation failed: {card_note}")
        _log(f"model-card: wrote {readme_path}")

        # --- 3. Modelfile (always produced) ----------------------------------
        system_prompt = None
        if isinstance(manifest, dict):
            system_prompt = manifest.get("system_prompt") or manifest.get("system")
        modelfile_path = write_modelfile(
            str(out_dir), summary["gguf"], manifest, system_prompt)
        summary["modelfile_path"] = modelfile_path
        _log(f"modelfile: wrote {modelfile_path}")

        # --- 4. HF push (opt-in) ---------------------------------------------
        if args.publish and args.hf_repo and not dry_run:
            _log(f"hf: pushing {out_dir} -> {args.hf_repo}")
            hf_result = push_to_hf(str(out_dir), args.hf_repo)
            summary["hf"] = hf_result
            if not hf_result.get("pushed"):
                _fail(4, summary, f"HF push failed: {hf_result.get('reason')}")
        else:
            summary["hf"] = {
                "pushed": False,
                "repo": args.hf_repo,
                "url": None,
                "reason": "dry-run (pass --publish + --hf to push)" if not args.publish
                          else "dry-run forced",
            }

        # --- 5. Ollama create (opt-in) ---------------------------------------
        if args.ollama_name and not dry_run:
            _log(f"ollama: create {args.ollama_name} -f {modelfile_path}")
            ollama_result = ollama_create(args.ollama_name, modelfile_path)
            summary["ollama"] = ollama_result
            if not ollama_result.get("created"):
                # Ollama is a convenience target; surface the reason but do not
                # fail the whole run (the model card + gguf already succeeded).
                _log(f"ollama: not created ({ollama_result.get('reason')})")
        elif args.ollama_name:
            summary["ollama"] = {
                "created": False,
                "name": args.ollama_name,
                "reason": "dry-run (Modelfile written; run `ollama create` manually)",
            }

    except SystemExit:
        raise
    except Exception as e:
        sys.stderr.write(traceback.format_exc())
        _fail(4, summary, f"publish raised: {e.__class__.__name__}: {e}")

    summary["ok"] = True
    summary["finished_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    _emit_summary(summary)
    sys.exit(0)


if __name__ == "__main__":
    main()
