// src/export-ollama.js
//
// S-2 — Generic Ollama integration for ANY .kolm artifact.
//
// This module is GENERIC. It does not bake in Trinity-specific paths or
// templates; it takes an artifact descriptor (with chat_template,
// system_prompt, stop_tokens, generation params) and produces:
//
//   * generateModelfile()  — pure string-builder; returns a Modelfile body
//                            with FROM/TEMPLATE/SYSTEM/PARAMETER stanzas.
//   * ollamaCreate()       — spawns `ollama create <name> -f <modelfile>`
//   * ollamaServe()        — spawns `ollama serve` + records the chosen port.
//                            Optional `pull` helper for the inverse direction
//                            (warm a model into the local Ollama cache from
//                            an already-created tag).
//
// Honest envelope: every spawn returns { ok, exit_code, stdout, stderr,
// wall_ms }. No silent fallbacks. If `ollama` is not on PATH we return the
// "install ollama" hint instead of pretending success.
//
// Tools that ALREADY exist on disk:
//   * tools/ollama-kolm/cli.js  — the W818-2 single-shot CLI for extracting
//                                 a .kolm bundle into an ollama-staging dir.
//     That CLI is bundle-aware (it unzips the .kolm via loadArtifact). This
//     module is FORMAT-only — generateModelfile() takes a plain artifact
//     descriptor, so the same function works whether the caller is unpacking
//     a .kolm bundle, a raw HF dir, or a freshly-quantized GGUF.

import { spawn, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

export const OLLAMA_EXPORT_VERSION = 'export-ollama-v1';

// Default Modelfile parameters. Callers can override per-artifact via the
// `parameters` arg; anything not provided falls back to these.
const DEFAULT_PARAMETERS = Object.freeze({
  temperature: 0.0,
  top_p: 0.95,
  top_k: 40,
  repeat_penalty: 1.1,
  num_ctx: 8192,
});

// Default ChatML template — the most common conversational format, used by
// Qwen2.5 / DeepSeek / Mistral-Instruct / etc. Callers MAY supply their own
// via artifact.chat_template; this default is the fallback.
const DEFAULT_CHATML_TEMPLATE = `{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ if .Prompt }}<|im_start|>user
{{ .Prompt }}<|im_end|>
{{ end }}<|im_start|>assistant
{{ .Response }}<|im_end|>
`;

// Escape a string for use inside a Modelfile triple-quoted block. Ollama's
// Modelfile parser uses """ as the delimiter so we replace embedded """ with
// '"""' (the Modelfile parser handles unicode escapes
// natively). We DON'T escape single quotes or backslashes.
function _escapeTripleQuoted(s) {
  return String(s || '').replace(/"""/g, '\\"\\"\\"');
}

// Quote a single-line string for a PARAMETER stop directive. Stop tokens are
// single-line; we wrap in double quotes and escape interior double quotes
// and backslashes.
function _quoteStopToken(t) {
  return '"' + String(t).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

/**
 * Pure string builder. Returns the Modelfile body as one string.
 *
 * Required artifact fields:
 *   - ggufPath          : path the FROM line points at (relative or absolute)
 *
 * Optional artifact fields (we read both top-level args AND the artifact
 * passport, so callers can pass either shape):
 *   - artifact.chat_template OR artifact.passport.chat_template
 *   - artifact.system_prompt OR artifact.passport.system_prompt
 *   - artifact.stop_tokens   OR artifact.passport.stop_tokens
 *   - artifact.parameters    OR artifact.passport.parameters
 *   - artifact.name, artifact.artifact_hash, artifact.base_model, etc. — emitted as # comments
 *
 * @param {object} cfg
 * @param {object} cfg.artifact      - Artifact descriptor (see above)
 * @param {string} cfg.ggufPath      - REQUIRED. FROM target.
 * @param {string} cfg.systemPrompt  - Override; falls back to artifact.system_prompt
 * @param {object} cfg.parameters    - Override; merges over artifact.parameters then DEFAULT_PARAMETERS
 * @returns {string} Modelfile body
 */
export function generateModelfile(cfg) {
  if (!cfg || typeof cfg !== 'object') {
    throw new Error('generateModelfile: cfg required');
  }
  const { artifact = {}, ggufPath, systemPrompt = null, parameters = {} } = cfg;
  if (!ggufPath) {
    throw new Error('generateModelfile: ggufPath required (FROM target)');
  }
  const passport = artifact.passport || {};
  const lines = [];

  // Header comment block — generic, no Trinity assumptions.
  lines.push('# Modelfile generated by kolm-forge ' + OLLAMA_EXPORT_VERSION);
  if (artifact.name) lines.push('# kolm-artifact: ' + artifact.name);
  if (artifact.artifact_hash) lines.push('# kolm-artifact-hash: ' + artifact.artifact_hash);
  if (artifact.base_model || passport.base_model) {
    lines.push('# kolm-base-model: ' + (artifact.base_model || passport.base_model));
  }
  if (artifact.distillation_method || passport.distillation_method) {
    lines.push('# kolm-distill: ' + (artifact.distillation_method || passport.distillation_method));
  }
  if (artifact.license || passport.license) {
    lines.push('# kolm-license: ' + (artifact.license || passport.license));
  }

  // FROM is REQUIRED. Ollama treats relative paths as relative to the
  // Modelfile location.
  lines.push('');
  lines.push('FROM ' + ggufPath);

  // TEMPLATE — pulled from artifact, falls back to ChatML default.
  const template = artifact.chat_template
    || passport.chat_template
    || artifact.template
    || passport.template
    || DEFAULT_CHATML_TEMPLATE;
  lines.push('');
  lines.push('TEMPLATE """' + _escapeTripleQuoted(template) + '"""');

  // SYSTEM — explicit override > artifact.system_prompt > passport.system_prompt
  // The empty string is treated as "no SYSTEM line" so a caller can opt out.
  const sys = systemPrompt != null
    ? systemPrompt
    : (artifact.system_prompt || passport.system_prompt || artifact.system || passport.system || '');
  if (sys && String(sys).length > 0) {
    lines.push('');
    lines.push('SYSTEM """' + _escapeTripleQuoted(sys) + '"""');
  }

  // PARAMETER block. Merge order:
  //   user-supplied parameters > artifact.parameters > passport.parameters > DEFAULT_PARAMETERS
  const merged = {
    ...DEFAULT_PARAMETERS,
    ...(passport.parameters || {}),
    ...(artifact.parameters || {}),
    ...(parameters || {}),
  };
  lines.push('');
  if (Number.isFinite(Number(merged.temperature))) lines.push('PARAMETER temperature ' + Number(merged.temperature));
  if (Number.isFinite(Number(merged.top_p))) lines.push('PARAMETER top_p ' + Number(merged.top_p));
  if (Number.isFinite(Number(merged.top_k))) lines.push('PARAMETER top_k ' + Math.floor(Number(merged.top_k)));
  if (Number.isFinite(Number(merged.repeat_penalty))) lines.push('PARAMETER repeat_penalty ' + Number(merged.repeat_penalty));
  if (Number.isFinite(Number(merged.num_ctx))) lines.push('PARAMETER num_ctx ' + Math.floor(Number(merged.num_ctx)));
  if (Number.isFinite(Number(merged.seed))) lines.push('PARAMETER seed ' + Math.floor(Number(merged.seed)));

  // Stop tokens — accept artifact.stop_tokens (preferred) or passport.stop_tokens.
  const stops = Array.isArray(artifact.stop_tokens)
    ? artifact.stop_tokens
    : (Array.isArray(passport.stop_tokens) ? passport.stop_tokens : []);
  for (const t of stops) {
    if (t == null || t === '') continue;
    lines.push('PARAMETER stop ' + _quoteStopToken(t));
  }

  // Attestation note — kept as a comment since Ollama has no enforcement hook.
  if (artifact.attestation || passport.attestation) {
    lines.push('');
    lines.push('# kolm-attestation: manifest-verify-only (ollama has no enforcement hook)');
  }

  return lines.join('\n') + '\n';
}

// ----------------------------------------------------------------------------
// Spawn helpers
// ----------------------------------------------------------------------------

function _ollamaBin() {
  // Explicit override always wins.
  if (process.env.OLLAMA_BIN && fs.existsSync(process.env.OLLAMA_BIN)) {
    return process.env.OLLAMA_BIN;
  }
  const isWin = process.platform === 'win32';
  const which = isWin ? 'where' : 'which';
  try {
    const r = spawnSync(which, ['ollama'], { encoding: 'utf8', timeout: 5000 });
    if (r.status === 0) {
      const line = (r.stdout || '').split(/\r?\n/).find(l => l.trim().length > 0);
      if (line) return line.trim();
    }
  } catch {}
  return null;
}

/**
 * Probe `ollama` availability. Returns { ok, binary, version, hint }.
 */
export function probeOllama() {
  const bin = _ollamaBin();
  if (!bin) {
    return {
      ok: false,
      missing: ['ollama'],
      hint: 'Install ollama from https://ollama.com/download (or set OLLAMA_BIN).',
    };
  }
  let version = null;
  try {
    const r = spawnSync(bin, ['--version'], { encoding: 'utf8', timeout: 5000, windowsHide: true });
    if (r.status === 0) {
      const m = String(r.stdout || r.stderr || '').match(/version[\s:]+([\d.]+)/i);
      version = m ? m[1] : (r.stdout || r.stderr || '').trim().split(/\r?\n/)[0];
    }
  } catch {}
  return { ok: true, binary: bin, version };
}

/**
 * Spawn `ollama create <modelName> -f <modelfilePath>`. Returns
 * { ok, exit_code, stdout, stderr, wall_ms, model_name }.
 */
export async function ollamaCreate({ modelName, modelfilePath, ollamaBin = null, timeoutMs = 10 * 60 * 1000 }) {
  if (!modelName) throw new Error('ollamaCreate: modelName required');
  if (!modelfilePath) throw new Error('ollamaCreate: modelfilePath required');
  if (!fs.existsSync(modelfilePath)) {
    return { ok: false, error: `modelfile_not_found: ${modelfilePath}` };
  }
  const bin = ollamaBin || _ollamaBin();
  if (!bin) {
    return { ok: false, error: 'ollama_not_found', hint: 'install ollama from https://ollama.com/download' };
  }
  const t0 = process.hrtime.bigint();
  const r = spawnSync(bin, ['create', modelName, '-f', modelfilePath], {
    encoding: 'utf8',
    timeout: timeoutMs,
    maxBuffer: 16 * 1024 * 1024,
    cwd: path.dirname(modelfilePath),
    windowsHide: true,
  });
  const wall_ms = Number(process.hrtime.bigint() - t0) / 1e6;
  if (r.error) {
    return { ok: false, error: 'spawn_failed', detail: r.error.message, wall_ms: Math.round(wall_ms) };
  }
  return {
    ok: r.status === 0,
    exit_code: r.status,
    stdout: (r.stdout || '').slice(-4096),
    stderr: (r.stderr || '').slice(-4096),
    model_name: modelName,
    wall_ms: Math.round(wall_ms),
  };
}

/**
 * Start `ollama serve` in the background. Returns { ok, pid, port } once the
 * process has started (does not wait for ready). Caller can poll
 * http://127.0.0.1:<port>/api/tags to confirm. If `modelName` is supplied we
 * also preload it via `ollama run <name> "<warmup>"` (one-shot).
 *
 * NOTE: `ollama serve` is normally launched once as a system service; this
 * helper is for ad-hoc dev runs (smoke tests, kolm serve --runtime ollama).
 * On systems where `ollama serve` is already running this call will fail
 * with a "port in use" stderr — that's expected and the caller should
 * detect it via probeOllamaReady().
 */
export async function ollamaServe({ port = 11434, ollamaBin = null, modelName = null, hostBind = '127.0.0.1' }) {
  const bin = ollamaBin || _ollamaBin();
  if (!bin) {
    return { ok: false, error: 'ollama_not_found', hint: 'install ollama' };
  }
  const env = { ...process.env, OLLAMA_HOST: `${hostBind}:${port}` };
  const child = spawn(bin, ['serve'], {
    env,
    stdio: ['ignore', 'pipe', 'pipe'],
    detached: true,
    windowsHide: true,
  });
  child.unref();
  // Buffer first 4 KB of stdout/stderr in case the spawn fails fast.
  let outBuf = '';
  let errBuf = '';
  child.stdout.on('data', (b) => { if (outBuf.length < 4096) outBuf += b.toString('utf8'); });
  child.stderr.on('data', (b) => { if (errBuf.length < 4096) errBuf += b.toString('utf8'); });
  return {
    ok: true,
    pid: child.pid,
    port,
    host: hostBind,
    base_url: `http://${hostBind}:${port}`,
    bin,
    note: modelName ? `model ${modelName} will be loaded on first request` : null,
    early_stdout: () => outBuf,
    early_stderr: () => errBuf,
  };
}

/**
 * One-shot probe: is `ollama serve` reachable at host:port?
 */
export async function probeOllamaReady({ port = 11434, host = '127.0.0.1', timeoutMs = 2000 }) {
  try {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), timeoutMs);
    const res = await fetch(`http://${host}:${port}/api/tags`, { signal: ctl.signal });
    clearTimeout(t);
    return { ok: res.ok, status: res.status };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

/**
 * Compose: generateModelfile + write to disk + ollamaCreate. Returns
 * { ok, modelfile_path, model_name, create_result, runtime_passport_hint }.
 *
 * The runtime_passport_hint is a stub passport row (status='estimated') that
 * a downstream caller can promote to 'tested' after running a real benchmark
 * against the ollama-served model.
 */
export async function exportOllama({
  artifact,
  ggufPath,
  outputDir,
  modelName = null,
  systemPrompt = null,
  parameters = {},
  skipCreate = false,
}) {
  if (!artifact || !ggufPath || !outputDir) {
    throw new Error('exportOllama: artifact, ggufPath, outputDir required');
  }
  fs.mkdirSync(outputDir, { recursive: true });
  // Default the FROM path to a relative reference if the gguf sits inside
  // outputDir, otherwise use the absolute path.
  const absGguf = path.resolve(ggufPath);
  const absOut = path.resolve(outputDir);
  const fromRef = absGguf.startsWith(absOut + path.sep)
    ? './' + path.relative(absOut, absGguf).split(path.sep).join('/')
    : absGguf;
  const body = generateModelfile({
    artifact,
    ggufPath: fromRef,
    systemPrompt,
    parameters,
  });
  const modelfilePath = path.join(outputDir, 'Modelfile');
  fs.writeFileSync(modelfilePath, body, 'utf8');
  const name = modelName
    || artifact.name
    || (artifact.passport && artifact.passport.name)
    || ('kolm-' + (artifact.artifact_hash ? String(artifact.artifact_hash).slice(0, 8) : 'artifact'));

  let create = null;
  if (!skipCreate) {
    const probe = probeOllama();
    if (probe.ok) {
      create = await ollamaCreate({ modelName: name, modelfilePath });
    } else {
      create = { ok: false, error: 'ollama_not_installed', hint: probe.hint, skipped: true };
    }
  }
  // Estimated passport hint — caller can promote to tested after benchmark.
  const passportHint = {
    target_id: `ollama-${name}`,
    status: 'estimated',
    runtime: 'ollama',
    runtime_version: 'unknown',
    precision: 'q4_k_m',  // common default; caller can override
    memory_mb: fs.existsSync(absGguf) ? Math.round(fs.statSync(absGguf).size / 1024 / 1024) : null,
    latency_p50_ms: null,
    latency_p95_ms: null,
    tok_s: null,
    quality_delta: null,
    fallback: 'gguf-q4_k_m-llama.cpp',
  };
  return {
    ok: true,
    modelfile_path: modelfilePath,
    model_name: name,
    from_ref: fromRef,
    body,
    create_result: create,
    runtime_passport_hint: passportHint,
    forge_version: OLLAMA_EXPORT_VERSION,
  };
}

export default {
  OLLAMA_EXPORT_VERSION,
  generateModelfile,
  ollamaCreate,
  ollamaServe,
  probeOllama,
  probeOllamaReady,
  exportOllama,
};
