// W807-2 - mid-response teacher splice + W807-5 per-tenant latency budget.
//
// When the streaming entropy window (src/confidence-router.js) exceeds the
// active threshold, the runtime calls spliceToTeacher() to ask the teacher
// to continue from the student's current token state. The function returns
// a structured envelope that the runtime (orchestrator's src/runtime-wrap.js
// - owned by W809) merges into the response metadata schema (W807-3).
//
// Honest-by-default contract:
//
//   - Teacher unreachable / non-2xx / timeout → finish-locally + stamp
//     fallback_failed:true on the envelope. The function NEVER throws
//     into the generation path - the worst case is "you get the student's
//     completion plus an error stamp."
//
//   - Per-tenant max_splice_delay_ms (W807-5). When exceeded → degrade-to-
//     local and write a `splice_budget_exceeded` warning event. The budget
//     comes from (in priority order): explicit opts.max_splice_delay_ms,
//     env KOLM_MAX_SPLICE_DELAY_MS, tenant-config getMaxSpliceDelayMs(),
//     hard default 8_000 ms.
//
//   - No real teacher call here - the actual teacher HTTP call is a
//     pluggable callback (opts.teacher_call). Tests inject a deterministic
//     stub; production wires the same routing-adapter src/runtime-wrap.js
//     uses for the per-call route. This split is what lets us unit-test
//     the splice envelope without binding to a network.
//
// Response metadata schema (W807-3):
//
//   {
//     local_tokens: number,        // tokens generated by the student
//     teacher_tokens: number,      // tokens generated by the teacher
//     local_ratio: number,         // local / (local + teacher) ∈ [0,1]
//     splice_events: [             // chronological list
//       { at_token, reason, latency_ms, ok, error? }
//     ],
//     threshold_used: number,      // numeric nats threshold the router used
//     threshold_profile: string?,  // profile name (or null if raw number)
//     fallback_failed: boolean,    // true iff ≥1 splice attempt failed
//     version: 'w807-v1'
//   }

import { VERSION as CR_VERSION } from './confidence-router.js';

export const VERSION = 'w807-v1';

// Hard default; superseded by opts → env → tenant-config in that order.
export const DEFAULT_MAX_SPLICE_DELAY_MS = 8_000;
export const TEACHER_SPLICE_LIMITS = Object.freeze({
  max_budget_ms: 60_000,
  max_tokens_so_far: 8192,
  max_token_chars: 2000,
  max_prompt_chars: 20000,
  max_teacher_text_chars: 20000,
  max_teacher_tokens: 8192,
  max_id_chars: 160,
  max_error_chars: 120,
});

// In-memory per-tenant override registry. Production callers may set this
// at startup; tests use it to inject a per-test budget without env-var
// churn. Persisted overrides belong in src/settings.js (orchestrator-owned).
const TENANT_BUDGETS = new Map();
const UNSAFE_IDS = new Set(['__proto__', 'constructor', 'prototype']);

function _safeText(v, max) {
  const s = String(v == null ? '' : v).replace(/[\u0000-\u001f\u007f]+/g, ' ').trim();
  return s.length > max ? s.slice(0, max) : s;
}

function _safeId(v, fallback = null) {
  const raw = _safeText(v == null ? '' : v, TEACHER_SPLICE_LIMITS.max_id_chars);
  if (!raw || UNSAFE_IDS.has(raw)) return fallback;
  const s = raw
    .replace(/[^\w:.-]+/g, '_')
    .replace(/^_+|_+$/g, '');
  if (!s || UNSAFE_IDS.has(s)) return fallback;
  return s;
}

function _safeErrorCode(v) {
  const s = _safeId(v, 'teacher_unreachable');
  return s && s.length <= TEACHER_SPLICE_LIMITS.max_error_chars ? s : 'teacher_unreachable';
}

function _clampBudget(v) {
  const n = Math.trunc(Number(v));
  if (!Number.isFinite(n) || n <= 0) return null;
  return Math.min(n, TEACHER_SPLICE_LIMITS.max_budget_ms);
}

/**
 * Set a per-tenant splice-latency budget (ms). Pass null to clear.
 * @param {string} tenant_id
 * @param {number|null} budgetMs
 */
export function setMaxSpliceDelayMs(tenant_id, budgetMs) {
  const tenant = _safeId(tenant_id);
  if (!tenant) return;
  if (budgetMs == null) { TENANT_BUDGETS.delete(tenant); return; }
  const n = _clampBudget(budgetMs);
  if (n != null) TENANT_BUDGETS.set(tenant, n);
}

/**
 * Read the effective splice-latency budget for a tenant. Priority:
 *   1. explicit_override
 *   2. env KOLM_MAX_SPLICE_DELAY_MS
 *   3. TENANT_BUDGETS map
 *   4. DEFAULT_MAX_SPLICE_DELAY_MS
 *
 * @param {string} tenant_id
 * @param {number} [explicit_override]
 * @returns {number} budget in ms
 */
export function getMaxSpliceDelayMs(tenant_id, explicit_override) {
  const explicit = _clampBudget(explicit_override);
  if (explicit != null) return explicit;
  const env = _clampBudget(process.env.KOLM_MAX_SPLICE_DELAY_MS);
  if (env != null) return env;
  const tenant = _safeId(tenant_id);
  if (tenant && TENANT_BUDGETS.has(tenant)) return TENANT_BUDGETS.get(tenant);
  return DEFAULT_MAX_SPLICE_DELAY_MS;
}

// Lightweight Promise+timeout. Rejects with a tagged error so the splice
// envelope can encode the reason precisely (vs swallowing into a generic
// "teacher_unreachable").
function withTimeout(promise, ms, code) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => {
      const err = new Error('splice timeout ' + ms + 'ms');
      err.code = code || 'splice_timeout';
      reject(err);
    }, ms);
    // node's setTimeout returns a Timeout object - .unref() exists in node
    // but not in browser. Guard so this file stays bundleable.
    try { timer && timer.unref && timer.unref(); } catch (_) {} // deliberate: cleanup
  });
  return Promise.race([promise, timeout]).finally(() => {
    try { clearTimeout(timer); } catch (_) {} // deliberate: cleanup
  });
}

function _coerceTokens(t) {
  if (t == null) return [];
  if (Array.isArray(t)) return t.slice(0, TEACHER_SPLICE_LIMITS.max_tokens_so_far)
    .map((x) => _safeText(x, TEACHER_SPLICE_LIMITS.max_token_chars));
  if (typeof t === 'string') return [_safeText(t, TEACHER_SPLICE_LIMITS.max_token_chars)];
  return [];
}

function _now() { return Date.now(); }

/**
 * Splice from the student to the teacher mid-response.
 *
 * @param {Object} opts
 * @param {Array<string>|string} opts.tokens_so_far Tokens the student already
 *                                                  emitted (most recent last).
 * @param {string} opts.prompt                      Original user prompt.
 * @param {string} [opts.teacher_id]                Logical teacher identifier
 *                                                  ('anthropic'|'openai'|...).
 * @param {number} [opts.budget_ms]                 Per-call override.
 * @param {string} [opts.tenant_id]                 For budget lookup.
 * @param {string} [opts.threshold_profile]         Pass-through tag.
 * @param {number} [opts.threshold_used]            Pass-through tag.
 * @param {Function} [opts.teacher_call]            async ({prompt, tokens_so_far,
 *                                                   teacher_id, signal}) →
 *                                                   {text|tokens, completion_tokens?}
 *                                                  If absent, returns
 *                                                  {ok:false, error:'no_teacher_call_wired'}.
 * @returns {Promise<Object>} W807-3 schema (single-splice flavor - the
 *          orchestrator merges multiple calls into a top-level envelope).
 */
export async function spliceToTeacher(opts = {}) {
  const tokensSoFar = _coerceTokens(opts.tokens_so_far);
  const prompt = _safeText(opts.prompt || '', TEACHER_SPLICE_LIMITS.max_prompt_chars);
  const teacher_id = _safeId(opts.teacher_id, 'default');
  const tenant_id = _safeId(opts.tenant_id, null);
  const threshold_used = Number.isFinite(Number(opts.threshold_used)) ? Number(opts.threshold_used) : null;
  const threshold_profile = _safeId(opts.threshold_profile, null);
  const budget = getMaxSpliceDelayMs(tenant_id, opts.budget_ms);
  const startedAt = _now();
  const at_token = tokensSoFar.length;
  const reason = _safeId(opts.reason, 'entropy_window_exceeded');

  const baseEnvelope = {
    local_tokens: tokensSoFar.length,
    teacher_tokens: 0,
    local_ratio: 1,
    splice_events: [],
    threshold_used,
    threshold_profile,
    fallback_failed: false,
    version: VERSION,
    confidence_router_version: CR_VERSION,
  };

  if (typeof opts.teacher_call !== 'function') {
    const latency = _now() - startedAt;
    return {
      ...baseEnvelope,
      fallback_failed: true,
      splice_events: [{
        at_token,
        reason,
        latency_ms: latency,
        ok: false,
        error: 'no_teacher_call_wired',
      }],
    };
  }

  // Budget exceeded BEFORE we even start? Defensive - caller may have
  // queued for a long time. Degrade-to-local immediately + warn.
  // (Most production paths will never hit this; main check is the timeout
  // wrapping the teacher_call below.)
  if (!Number.isFinite(budget) || budget <= 0) {
    return {
      ...baseEnvelope,
      fallback_failed: true,
      splice_events: [{
        at_token,
        reason: 'splice_budget_exceeded',
        latency_ms: _now() - startedAt,
        ok: false,
        error: 'invalid_budget',
        budget_ms: budget,
      }],
    };
  }

  let teacherResult = null;
  let teacherError = null;
  try {
    teacherResult = await withTimeout(
      Promise.resolve().then(() => opts.teacher_call({
        prompt,
        tokens_so_far: tokensSoFar,
        teacher_id,
      })),
      budget,
      'splice_budget_exceeded',
    );
  } catch (e) {
    teacherError = e;
  }

  const latency = _now() - startedAt;

  if (teacherError) {
    const errCode = _safeErrorCode(teacherError.code || 'teacher_unreachable');
    // Per W807-5, emit a warning event into the event-store so operators see
    // the budget-exceeded count on the confidence dashboard. Failure to
    // write the warning is non-fatal - the splice envelope is authoritative.
    if (errCode === 'splice_budget_exceeded' && tenant_id) {
      try {
        const es = await import('./event-store.js');
        await es.appendEvent({
          tenant_id,
          namespace: _safeId(opts.namespace, 'default'),
          provider: 'kolm-confidence-router',
          vendor: 'kolm',
          model: 'router/splice',
          workflow_id: 'splice:budget_exceeded',
          status: 'timeout',
          feedback: JSON.stringify({
            kind: 'splice_budget_exceeded',
            budget_ms: budget,
            latency_ms: latency,
            teacher_id,
            threshold_used,
            threshold_profile,
            version: VERSION,
          }),
        });
      } catch (_) { /* best-effort */ }
    }
    return {
      ...baseEnvelope,
      fallback_failed: true,
      splice_events: [{
        at_token,
        reason: errCode === 'splice_budget_exceeded' ? 'splice_budget_exceeded' : reason,
        latency_ms: latency,
        ok: false,
        error: errCode,
        budget_ms: budget,
      }],
    };
  }

  if (!teacherResult || typeof teacherResult !== 'object') {
    return {
      ...baseEnvelope,
      fallback_failed: true,
      splice_events: [{
        at_token,
        reason,
        latency_ms: latency,
        ok: false,
        error: 'teacher_returned_no_payload',
      }],
    };
  }

  const teacherTokens = Number.isFinite(Number(teacherResult.completion_tokens))
    ? Math.min(TEACHER_SPLICE_LIMITS.max_teacher_tokens, Math.max(0, Math.trunc(Number(teacherResult.completion_tokens))))
    : (Array.isArray(teacherResult.tokens)
      ? Math.min(TEACHER_SPLICE_LIMITS.max_teacher_tokens, teacherResult.tokens.length)
      : (typeof teacherResult.text === 'string'
        // Cheap token estimate: char_count / 4. Real tokenization happens
        // in the orchestrator; this fallback only matters when the teacher
        // adapter omits completion_tokens.
        ? Math.min(TEACHER_SPLICE_LIMITS.max_teacher_tokens, Math.max(1, Math.ceil(teacherResult.text.length / 4)))
        : 0));

  const totalTokens = tokensSoFar.length + teacherTokens;
  const local_ratio = totalTokens === 0 ? 1 : tokensSoFar.length / totalTokens;

  return {
    ...baseEnvelope,
    teacher_tokens: teacherTokens,
    local_ratio,
    splice_events: [{
      at_token,
      reason,
      latency_ms: latency,
      ok: true,
      teacher_id,
    }],
    teacher_payload: {
      text: typeof teacherResult.text === 'string'
        ? _safeText(teacherResult.text, TEACHER_SPLICE_LIMITS.max_teacher_text_chars)
        : null,
      tokens: Array.isArray(teacherResult.tokens)
        ? teacherResult.tokens.slice(0, TEACHER_SPLICE_LIMITS.max_teacher_tokens)
            .map((x) => _safeText(x, TEACHER_SPLICE_LIMITS.max_token_chars))
        : null,
    },
    fallback_failed: false,
  };
}

/**
 * Reset the in-memory tenant-budget registry. Test seam - production never
 * calls this.
 */
export function _resetTenantBudgetsForTests() {
  TENANT_BUDGETS.clear();
}

export default {
  VERSION,
  DEFAULT_MAX_SPLICE_DELAY_MS,
  TEACHER_SPLICE_LIMITS,
  spliceToTeacher,
  getMaxSpliceDelayMs,
  setMaxSpliceDelayMs,
  _resetTenantBudgetsForTests,
};
