/** @type {import('next').NextConfig} */

// Legacy URL map ported 1:1 from the static site's vercel.json so no inbound
// link 404s when kolm.ai cuts over from the static public/ build to this Next
// app. Every entry is a permanent (308) redirect, mirroring Vercel's
// `permanent: true`. Next.js evaluates redirects before the filesystem routes,
// so the one static redirect that now collides with a real page in this app
// (`/customers`, which is a first-class route here) is intentionally dropped -
// keeping it would shadow the new page. The `:path(.+)` sources match any
// sub-path (across slashes), exactly as path-to-regexp does on Vercel; Next
// does not append the unused capture to the destination query for redirects.
const legacyRedirects = [
    { source: "/openapi.json", destination: "/docs", permanent: true },
    { source: "/about", destination: "/", permanent: true },
    { source: "/about-the-assistant", destination: "/docs", permanent: true },
    { source: "/account", destination: "/", permanent: true },
    { source: "/admin", destination: "/", permanent: true },
    { source: "/agents", destination: "/how-it-works", permanent: true },
    { source: "/airgap", destination: "/security", permanent: true },
    { source: "/anatomy", destination: "/how-it-works", permanent: true },
    { source: "/api", destination: "/docs", permanent: true },
    { source: "/api-routes.json", destination: "/docs", permanent: true },
    { source: "/architecture", destination: "/platform", permanent: true },
    { source: "/articles", destination: "/", permanent: true },
    { source: "/artifacts", destination: "/verify", permanent: true },
    { source: "/ask", destination: "/contact", permanent: true },
    { source: "/atlas", destination: "/research", permanent: true },
    { source: "/audit", destination: "/transparency-log", permanent: true },
    { source: "/audit-log", destination: "/transparency-log", permanent: true },
    { source: "/badge", destination: "/verify", permanent: true },
    { source: "/bench", destination: "/research", permanent: true },
    { source: "/benchmarks", destination: "/research", permanent: true },
    { source: "/blog", destination: "/", permanent: true },
    { source: "/book-demo", destination: "/contact", permanent: true },
    { source: "/bounties", destination: "/", permanent: true },
    { source: "/bounty", destination: "/", permanent: true },
    { source: "/brand", destination: "/", permanent: true },
    { source: "/build-your-own", destination: "/how-it-works", permanent: true },
    { source: "/builder", destination: "/how-it-works", permanent: true },
    { source: "/byoc", destination: "/enterprise", permanent: true },
    { source: "/capture", destination: "/how-it-works", permanent: true },
    { source: "/captures", destination: "/how-it-works", permanent: true },
    { source: "/case-studies", destination: "/enterprise", permanent: true },
    { source: "/cerebras-teacher", destination: "/how-it-works", permanent: true },
    { source: "/ci", destination: "/docs", permanent: true },
    { source: "/cli", destination: "/docs", permanent: true },
    { source: "/cloud", destination: "/platform", permanent: true },
    { source: "/code-gen", destination: "/how-it-works", permanent: true },
    { source: "/community", destination: "/", permanent: true },
    { source: "/community-github", destination: "https://github.com/kolm-ai/kolm", permanent: true },
    { source: "/compare", destination: "/how-it-works", permanent: true },
    { source: "/compile", destination: "/how-it-works", permanent: true },
    { source: "/compliance", destination: "/trust", permanent: true },
    { source: "/compliance-packs", destination: "/trust", permanent: true },
    { source: "/compute", destination: "/platform", permanent: true },
    { source: "/cookbook", destination: "/docs", permanent: true },
    { source: "/customer-support", destination: "/contact", permanent: true },
    { source: "/datasets", destination: "/research", permanent: true },
    { source: "/defense", destination: "/security", permanent: true },
    { source: "/defense-v2", destination: "/security", permanent: true },
    { source: "/demo", destination: "/how-it-works", permanent: true },
    { source: "/demo-90s", destination: "/how-it-works", permanent: true },
    { source: "/demo-live", destination: "/how-it-works", permanent: true },
    { source: "/design-system", destination: "/", permanent: true },
    { source: "/developers", destination: "/docs", permanent: true },
    { source: "/device", destination: "/docs", permanent: true },
    { source: "/device-transfer", destination: "/docs", permanent: true },
    { source: "/devtools", destination: "/docs", permanent: true },
    { source: "/devtools-v2", destination: "/docs", permanent: true },
    { source: "/distill", destination: "/how-it-works", permanent: true },
    { source: "/download", destination: "/docs", permanent: true },
    { source: "/dpia", destination: "/security", permanent: true },
    { source: "/drift", destination: "/how-it-works", permanent: true },
    { source: "/edge", destination: "/platform", permanent: true },
    { source: "/education", destination: "/enterprise", permanent: true },
    { source: "/eu", destination: "/trust", permanent: true },
    { source: "/eu-sovereign", destination: "/trust", permanent: true },
    { source: "/events", destination: "/", permanent: true },
    { source: "/evolve", destination: "/how-it-works", permanent: true },
    { source: "/faq", destination: "/docs", permanent: true },
    { source: "/finance", destination: "/enterprise", permanent: true },
    { source: "/finance-v2", destination: "/enterprise", permanent: true },
    { source: "/fintech", destination: "/enterprise", permanent: true },
    { source: "/fleet", destination: "/platform", permanent: true },
    { source: "/for", destination: "/enterprise", permanent: true },
    { source: "/forge", destination: "/how-it-works", permanent: true },
    { source: "/format", destination: "/docs", permanent: true },
    { source: "/foundations", destination: "/how-it-works", permanent: true },
    { source: "/frontier-stack", destination: "/platform", permanent: true },
    { source: "/frozen-eval", destination: "/research", permanent: true },
    { source: "/gateway", destination: "/platform", permanent: true },
    { source: "/gateway-migration", destination: "/how-it-works", permanent: true },
    { source: "/glossary", destination: "/docs", permanent: true },
    { source: "/gov", destination: "/enterprise", permanent: true },
    { source: "/government", destination: "/enterprise", permanent: true },
    { source: "/hall-of-fame", destination: "/security", permanent: true },
    { source: "/hardware", destination: "/platform", permanent: true },
    { source: "/health-insurance", destination: "/enterprise", permanent: true },
    { source: "/healthcare", destination: "/enterprise", permanent: true },
    { source: "/healthcare-v2", destination: "/enterprise", permanent: true },
    { source: "/helm", destination: "/enterprise", permanent: true },
    { source: "/hipaa-mapping", destination: "/trust", permanent: true },
    { source: "/hobbyist", destination: "/pricing", permanent: true },
    { source: "/how-vs-anthropic", destination: "/how-it-works", permanent: true },
    { source: "/how-vs-diy", destination: "/how-it-works", permanent: true },
    { source: "/how-vs-hyperscaler", destination: "/how-it-works", permanent: true },
    { source: "/how-vs-lorax", destination: "/how-it-works", permanent: true },
    { source: "/how-vs-openai-fine-tune", destination: "/how-it-works", permanent: true },
    { source: "/how-vs-openpipe", destination: "/how-it-works", permanent: true },
    { source: "/how-vs-predibase", destination: "/how-it-works", permanent: true },
    { source: "/hub", destination: "/", permanent: true },
    { source: "/install", destination: "/docs", permanent: true },
    { source: "/insurance", destination: "/enterprise", permanent: true },
    { source: "/insure", destination: "/enterprise", permanent: true },
    { source: "/integrations", destination: "/docs", permanent: true },
    { source: "/iso-27001", destination: "/security", permanent: true },
    { source: "/k-score", destination: "/research", permanent: true },
    { source: "/k-score-calibration", destination: "/research", permanent: true },
    { source: "/k-score-explained", destination: "/research", permanent: true },
    { source: "/kolm-auto-pilot", destination: "/how-it-works", permanent: true },
    { source: "/kscore-bench", destination: "/research", permanent: true },
    { source: "/kscore-leaderboard", destination: "/research", permanent: true },
    { source: "/labs", destination: "/research", permanent: true },
    { source: "/lang", destination: "/docs", permanent: true },
    { source: "/leaderboard", destination: "/research", permanent: true },
    { source: "/learn", destination: "/docs", permanent: true },
    { source: "/legal", destination: "/terms", permanent: true },
    { source: "/legal-v2", destination: "/terms", permanent: true },
    { source: "/legal/sla.pdf", destination: "/enterprise", permanent: true },
    { source: "/license", destination: "/terms", permanent: true },
    { source: "/limits", destination: "/pricing", permanent: true },
    { source: "/login", destination: "/", permanent: true },
    { source: "/manifesto", destination: "/", permanent: true },
    { source: "/marketplace", destination: "/platform", permanent: true },
    { source: "/merge", destination: "/how-it-works", permanent: true },
    { source: "/migrate", destination: "/how-it-works", permanent: true },
    { source: "/models", destination: "/platform", permanent: true },
    { source: "/msa", destination: "/enterprise", permanent: true },
    { source: "/nonprofits", destination: "/pricing", permanent: true },
    { source: "/office-hours", destination: "/", permanent: true },
    { source: "/onboard", destination: "/docs", permanent: true },
    { source: "/onboarding", destination: "/docs", permanent: true },
    { source: "/openai", destination: "/how-it-works", permanent: true },
    { source: "/openai-migration", destination: "/how-it-works", permanent: true },
    { source: "/partners", destination: "/enterprise", permanent: true },
    { source: "/password-reset", destination: "/", permanent: true },
    { source: "/playground", destination: "/docs", permanent: true },
    { source: "/press", destination: "/", permanent: true },
    { source: "/product", destination: "/how-it-works", permanent: true },
    { source: "/proof", destination: "/verify", permanent: true },
    { source: "/quickstart", destination: "/docs", permanent: true },
    { source: "/r", destination: "/verify", permanent: true },
    { source: "/recall", destination: "/how-it-works", permanent: true },
    { source: "/receipt", destination: "/verify", permanent: true },
    { source: "/recipe-classes", destination: "/docs", permanent: true },
    { source: "/recipes", destination: "/docs", permanent: true },
    { source: "/registry", destination: "/docs", permanent: true },
    { source: "/retail", destination: "/enterprise", permanent: true },
    { source: "/roadmap", destination: "/changelog", permanent: true },
    { source: "/roi", destination: "/pricing", permanent: true },
    { source: "/run", destination: "/how-it-works", permanent: true },
    { source: "/runtimes", destination: "/platform", permanent: true },
    { source: "/saas", destination: "/enterprise", permanent: true },
    { source: "/safety", destination: "/security", permanent: true },
    { source: "/sbom", destination: "/security", permanent: true },
    { source: "/sdks", destination: "/docs", permanent: true },
    { source: "/security/architecture.pdf", destination: "/security", permanent: true },
    { source: "/security/bug-bounty", destination: "/security", permanent: true },
    { source: "/security/dpia-template.docx", destination: "/security", permanent: true },
    { source: "/security/hof", destination: "/security", permanent: true },
    { source: "/security/incident-response", destination: "/security", permanent: true },
    { source: "/security/iso-27001", destination: "/security", permanent: true },
    { source: "/security/membership-inference", destination: "/security", permanent: true },
    { source: "/security/model-poisoning", destination: "/security", permanent: true },
    { source: "/security/posture", destination: "/security", permanent: true },
    { source: "/security/prompt-extraction", destination: "/security", permanent: true },
    { source: "/security/questionnaire", destination: "/checks", permanent: true },
    { source: "/security/red-team", destination: "/security", permanent: true },
    { source: "/security/sbom", destination: "/security", permanent: true },
    { source: "/security/soc2-type2", destination: "/trust", permanent: true },
    { source: "/security/sub-processors", destination: "/subprocessors", permanent: true },
    { source: "/security/threat-model.pdf", destination: "/security", permanent: true },
    { source: "/self-host", destination: "/enterprise", permanent: true },
    { source: "/serve", destination: "/platform", permanent: true },
    { source: "/settings", destination: "/", permanent: true },
    { source: "/setup", destination: "/docs", permanent: true },
    { source: "/setup-with-ai", destination: "/docs", permanent: true },
    { source: "/shortcuts", destination: "/docs", permanent: true },
    { source: "/showcase", destination: "/enterprise", permanent: true },
    { source: "/signin", destination: "/", permanent: true },
    { source: "/slsa", destination: "/security", permanent: true },
    { source: "/solutions", destination: "/enterprise", permanent: true },
    { source: "/solutions/teams", destination: "/enterprise", permanent: true },
    { source: "/sovereign-ai", destination: "/trust", permanent: true },
    { source: "/spec", destination: "/docs", permanent: true },
    { source: "/spec-grammar", destination: "/docs", permanent: true },
    { source: "/start", destination: "/docs", permanent: true },
    { source: "/status/history", destination: "/status", permanent: true },
    { source: "/studio", destination: "/platform", permanent: true },
    { source: "/sustainability", destination: "/", permanent: true },
    { source: "/taxonomy", destination: "/docs", permanent: true },
    { source: "/teams", destination: "/enterprise", permanent: true },
    { source: "/teams-accept", destination: "/", permanent: true },
    { source: "/telemetry", destination: "/privacy", permanent: true },
    { source: "/templates", destination: "/docs", permanent: true },
    { source: "/threat-model", destination: "/security/threat-model", permanent: true },
    { source: "/tos", destination: "/terms", permanent: true },
    { source: "/train", destination: "/how-it-works", permanent: true },
    { source: "/training", destination: "/how-it-works", permanent: true },
    { source: "/troubleshooting", destination: "/docs", permanent: true },
    { source: "/tui", destination: "/docs", permanent: true },
    { source: "/tunnels", destination: "/docs", permanent: true },
    { source: "/tutorials", destination: "/docs", permanent: true },
    { source: "/university", destination: "/docs", permanent: true },
    { source: "/upgrade", destination: "/pricing", permanent: true },
    { source: "/use-cases", destination: "/how-it-works", permanent: true },
    { source: "/value-loop", destination: "/how-it-works", permanent: true },
    { source: "/verify-cli", destination: "/verify", permanent: true },
    { source: "/verify-prod", destination: "/verify", permanent: true },
    { source: "/verticals", destination: "/enterprise", permanent: true },
    { source: "/vs", destination: "/how-it-works", permanent: true },
    { source: "/vs-fine-tune", destination: "/how-it-works", permanent: true },
    { source: "/vs-hindsight", destination: "/how-it-works", permanent: true },
    { source: "/vs-langsmith", destination: "/how-it-works", permanent: true },
    { source: "/vs-mem0", destination: "/how-it-works", permanent: true },
    { source: "/vs-ollama", destination: "/how-it-works", permanent: true },
    { source: "/vs-openai", destination: "/how-it-works", permanent: true },
    { source: "/vs-openai-fine-tune", destination: "/how-it-works", permanent: true },
    { source: "/vs-openpipe", destination: "/how-it-works", permanent: true },
    { source: "/vs-predibase", destination: "/how-it-works", permanent: true },
    { source: "/vs-rag", destination: "/how-it-works", permanent: true },
    { source: "/vs-together", destination: "/how-it-works", permanent: true },
    { source: "/what-is-an-ai-compiler", destination: "/how-it-works", permanent: true },
    { source: "/whitepaper", destination: "/research", permanent: true },
    { source: "/why-kolm", destination: "/how-it-works", permanent: true },
    { source: "/why-now", destination: "/how-it-works", permanent: true },
    { source: "/wrapper", destination: "/how-it-works", permanent: true },
    { source: "/account/:path(.+)", destination: "/", permanent: true },
    { source: "/articles/:path(.+)", destination: "/", permanent: true },
    { source: "/artifacts/:path(.+)", destination: "/verify", permanent: true },
    { source: "/bench/:path(.+)", destination: "/research", permanent: true },
    { source: "/benchmarks/:path(.+)", destination: "/research", permanent: true },
    { source: "/blog/:path(.+)", destination: "/", permanent: true },
    { source: "/brand/:path(.+)", destination: "/", permanent: true },
    { source: "/case-studies/:path(.+)", destination: "/enterprise", permanent: true },
    { source: "/community/:path(.+)", destination: "/", permanent: true },
    { source: "/compare/:path(.+)", destination: "/how-it-works", permanent: true },
    { source: "/compile/:path(.+)", destination: "/how-it-works", permanent: true },
    { source: "/compliance/:path(.+)", destination: "/trust", permanent: true },
    { source: "/cookbook/:path(.+)", destination: "/docs", permanent: true },
    { source: "/device-transfer/:path(.+)", destination: "/docs", permanent: true },
    { source: "/device/:path(.+)", destination: "/docs", permanent: true },
    { source: "/docs/:path(.+)", destination: "/docs", permanent: true },
    { source: "/enterprise/:path(.+)", destination: "/enterprise", permanent: true },
    { source: "/finance/:path(.+)", destination: "/enterprise", permanent: true },
    { source: "/for/:path(.+)", destination: "/enterprise", permanent: true },
    { source: "/format/:path(.+)", destination: "/docs", permanent: true },
    { source: "/foundations/:path(.+)", destination: "/how-it-works", permanent: true },
    { source: "/healthcare/:path(.+)", destination: "/enterprise", permanent: true },
    { source: "/install/:path(.+)", destination: "/docs", permanent: true },
    { source: "/insurance/:path(.+)", destination: "/enterprise", permanent: true },
    { source: "/integrations/:path(.+)", destination: "/docs", permanent: true },
    { source: "/lang/:path(.+)", destination: "/docs", permanent: true },
    { source: "/learn/:path(.+)", destination: "/docs", permanent: true },
    { source: "/legal/:path(.+)", destination: "/terms", permanent: true },
    { source: "/marketplace/:path(.+)", destination: "/platform", permanent: true },
    { source: "/migrate/:path(.+)", destination: "/how-it-works", permanent: true },
    { source: "/onboard/:path(.+)", destination: "/docs", permanent: true },
    { source: "/partners/:path(.+)", destination: "/enterprise", permanent: true },
    { source: "/playground/:path(.+)", destination: "/docs", permanent: true },
    { source: "/pricing/:path(.+)", destination: "/pricing", permanent: true },
    { source: "/quickstart/:path(.+)", destination: "/docs", permanent: true },
    { source: "/r/:path(.+)", destination: "/verify", permanent: true },
    { source: "/registry/:path(.+)", destination: "/docs", permanent: true },
    { source: "/research/:path(.+)", destination: "/research", permanent: true },
    { source: "/spec/:path(.+)", destination: "/docs", permanent: true },
    { source: "/studio/:path(.+)", destination: "/platform", permanent: true },
    { source: "/training/:path(.+)", destination: "/how-it-works", permanent: true },
    { source: "/tutorials/:path(.+)", destination: "/docs", permanent: true },
    { source: "/university/:path(.+)", destination: "/docs", permanent: true },
    { source: "/use-cases/:path(.+)", destination: "/how-it-works", permanent: true },
    { source: "/verticals/:path(.+)", destination: "/enterprise", permanent: true },
    { source: "/vs/:path(.+)", destination: "/how-it-works", permanent: true },
    { source: "/soc2", destination: "/trust", permanent: true },
];

const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,

  // The live API surface (/v1/audit, /v1/verify, /health) is served by the
  // existing backend (Railway today, see MEMORY). During the migration the
  // Next app proxies those paths to the same origin the static site uses, so
  // the browser verifier and the audit endpoints keep working without a code
  // change at cutover. Override the upstream with KOLM_API_ORIGIN at build/run
  // time; default is the production origin.
  async rewrites() {
    // Proxy the API straight to the Railway backend - NOT to kolm.ai, which is
    // this very app after cutover (that would self-loop). Mirrors the static
    // site's vercel.json which rewrites /v1/* to the Railway origin directly.
    const apiOrigin = process.env.KOLM_API_ORIGIN || "https://kolmogorov-stack-production.up.railway.app";
    return [
      { source: "/v1/:path*", destination: `${apiOrigin}/v1/:path*` },
      { source: "/health", destination: `${apiOrigin}/health` },
      { source: "/ready", destination: `${apiOrigin}/ready` },
    ];
  },

  // Preserve every inbound link from the static-site era. Ported from
  // vercel.json (see `legacyRedirects` above) so the cutover is link-loss-free.
  async redirects() {
    return legacyRedirects;
  },

  async headers() {
    return [
      {
        // The self-hosted fonts are immutable; cache them hard.
        source: "/fonts/:font*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
    ];
  },
};

export default nextConfig;
